{"feed"=>
  {"xmlns:openSearch"=>"http://a9.com/-/spec/opensearchrss/1.0/",
   "xmlns:gd"=>"http://schemas.google.com/g/2005",
   "xmlns:x_trumba"=>"http://schemas.trumba.com/atom/x-trumba",
   "xmlns:gc"=>"http://base.google.com/cns/1.0",
   "xmlns"=>"http://www.w3.org/2005/Atom",
   "id"=>"http://uid.trumba.com/calendar/297210",
   "updated"=>"2016-12-17T13:26:27Z",
   "title"=>"Smithsonian Events",
   "subtitle"=>nil,
   "link"=>
    [{"rel"=>"alternate", "type"=>"text/html", "href"=>"http://www.si.edu/Events/Calendar/"},
     {"rel"=>"self", "type"=>"application/atom+xml", "href"=>"http://www.si.edu/Events/Calendar/.xml"}],
   "author"=>{"name"=>"Smithsonian Events"},
   "generator"=>"Trumba Calendar",
   "where"=>{"valueString"=>"Washington"},
   "entry"=>
    [{"id"=>"http://uid.trumba.com/event/118197560",
      "masterId"=>"http://uid.trumba.com/master/118197256",
      "published"=>"2016-12-29T14:00:00Z",
      "updated"=>"2016-12-29T14:00:00Z",
      "category"=>{"scheme"=>"http://schemas.google.com/g/2005#kind", "term"=>"http://schemas.google.com/g/2005#event"},
      "title"=>"Castle Highlights Tour",
      "content"=>
       "Thursday, December 29, 2016, 9&nbsp;&ndash;&nbsp;9:45am <br/><br/>Did you know that the Castle is the Smithsonian&#8217;s first and oldest building? Join us as one of our dynamic volunteer docents takes you on a tour to explore the highlights of the Smithsonian Castle. Come learn about the founding and early history of the Smithsonian; its original benefactor, James Smithson; and the incredible history and architecture of the Castle. Here is your opportunity to discover the treasured stories revealed within James Smithson&#39;s crypt, the Great Hall, and the West Wing. We&#8217;ll see you at the Castle!<br /> <br /> <strong>Year-Round:&#160; </strong><br /><ul> <li>Daily: 9 a.m. &amp; 1:30 p.m. </li></ul><br /><strong>Note</strong><br /> - Tour subject to docent availability; last-minute cancellations may occur. <br/><br/><b>Categories</b>:&nbsp;Gallery Talks &amp; Tours <br/><b>Sponsor</b>:&nbsp;<a href=\"http://si.edu/Museums/smithsonian-institution-building\" target=\"_blank\">Smithsonian Visitor Center</a> <br/><b>Venue</b>:&nbsp;Smithsonian Castle <br/><b>Event Location</b>:&nbsp;Meet at information desk <br/><b>Cost</b>:&nbsp;Free; walk-in <br/><br/>",
      "link"=>
       {"rel"=>"alternate",
        "type"=>"text/html",
        "href"=>"http://www.si.edu/Events/Calendar/?trumbaEmbed=view%3devent%26eventid%3d118197560"},
      "author"=>{"name"=>"Smithsonian Events"},
      "transparency"=>{"value"=>"http://schemas.google.com/g/2005#event.transparent"},
      "where"=>{"valueString"=>""},
      "when"=>{"startTime"=>"2016-12-29T14:00:00Z", "endTime"=>"2016-12-29T14:45:00Z"},
      "formatteddatetime"=>"Thursday, December 29, 2016, 9 - 9:45am",
      "notes"=>
       "Did you know that the Castle is the Smithsonian’s first and oldest building? Join us as one of our dynamic volunteer docents takes you on a tour to explore the highlights of the Smithsonian Castle. Come learn about the founding and early history of the Smithsonian; its original benefactor, James Smithson; and the incredible history and architecture of the Castle. Here is your opportunity to discover the treasured stories revealed within James Smithson's crypt, the Great Hall, and the West Wing. We’ll see you at the Castle!\n \n <b>Year-Round:&nbsp; </b><br /><ul> \t<li>Daily: 9 a.m. &amp; 1:30 p.m.</li> </ul><br /><b>Note</b>\n - Tour subject to docent availability; last-minute cancellations may occur.",
      "eventtype"=>"Smithsonian Event",
      "categories"=>"Gallery Talks & Tours",
      "categoriesicon"=>"https://www.trumba.com/i/DgAqUDE4t70GftmgIpGmgAvR.gif",
      "sponsor"=>"Smithsonian Visitor Center",
      "venue"=>"Smithsonian Castle",
      "eventlocation"=>"Meet at information desk",
      "cost"=>"Free; walk-in",
      "cateoryCalendar"=>"Smithsonian Castle siedu|Ongoing Tours"},
     {"id"=>"http://uid.trumba.com/event/117852624",
      "masterId"=>"http://uid.trumba.com/master/117852256",
      "published"=>"2016-12-29T15:00:00Z",
      "updated"=>"2016-12-29T15:00:00Z",
      "category"=>{"scheme"=>"http://schemas.google.com/g/2005#kind", "term"=>"http://schemas.google.com/g/2005#event"},
      "title"=>"Exhibition Interpreters/Navigators (throughout the day)",
      "content"=>
       "Thursday, December 29, 2016, 10am <br/><br/>Museum volunteer interpreters welcome visitors, answer questions, and help visitors navigate exhibitions. Interpreters may be stationed in several of the following exhibitions at various times throughout the day, subject to volunteer interpreter availability. <ul> <li><em>The David H. Koch Hall of Human Origins: What Does it Mean to be Human?</em> </li><li><em>The Sant Ocean Hall</em> </li></ul> <br/><br/><b>Categories</b>:&nbsp;Gallery Talks &amp; Tours <br/><b>Sponsor</b>:&nbsp;<a href=\"http://www.mnh.si.edu/\" target=\"_blank\">Natural History Museum</a> <br/><b>Venue</b>:&nbsp;Natural History Museum <br/><b>Event Location</b>:&nbsp;Ground Floor <br/><b>Cost</b>:&nbsp;Free <br/><b>More info</b>:&nbsp;<a href=\"http://qrius.si.edu/\" target=\"_blank\">qrius.si.edu</a> <br/><br/>",
      "link"=>
       {"rel"=>"alternate",
        "type"=>"text/html",
        "href"=>"http://www.si.edu/Events/Calendar/?trumbaEmbed=view%3devent%26eventid%3d117852624"},
      "author"=>{"name"=>"Smithsonian Events"},
      "transparency"=>{"value"=>"http://schemas.google.com/g/2005#event.transparent"},
      "where"=>{"valueString"=>""},
      "when"=>{"startTime"=>"2016-12-29T15:00:00Z", "endTime"=>"2016-12-29T15:00:00Z"},
      "formatteddatetime"=>"Thursday, December 29, 2016, 10am",
      "notes"=>
       "Museum volunteer interpreters welcome visitors, answer questions, and help visitors navigate exhibitions. Interpreters may be stationed in several of the following exhibitions at various times throughout the day, subject to volunteer interpreter availability. <ul> \t<li><em>The David H. Koch Hall of Human Origins: What Does it Mean to be Human?</em></li> \t<li><em>The Sant Ocean Hall</em></li> </ul>",
      "eventtype"=>"Smithsonian Event",
      "categories"=>"Gallery Talks & Tours",
      "categoriesicon"=>"https://www.trumba.com/i/DgAqUDE4t70GftmgIpGmgAvR.gif",
      "sponsor"=>"Natural History Museum",
      "venue"=>"Natural History Museum",
      "eventlocation"=>"Ground Floor",
      "cost"=>"Free",
      "cateoryCalendar"=>"Natural History Museum|Ongoing Tours & Activities",
      "weblink"=>"http://qrius.si.edu/"},
     {"id"=>"http://uid.trumba.com/event/113256645",
      "masterId"=>"http://uid.trumba.com/master/85792639",
      "published"=>"2016-12-29T15:00:00Z",
      "updated"=>"2016-12-29T15:00:00Z",
      "category"=>{"scheme"=>"http://schemas.google.com/g/2005#kind", "term"=>"http://schemas.google.com/g/2005#event"},
      "title"=>"Ride Simulators (throughout the day)",
      "content"=>
       "Thursday, December 29, 2016, 10am <br/><br/><strong>Ride Simulators:</strong> (ride approximately 5 min.)<br /> Take an exciting virtual trip on board one of four simulators. Experience the thrill of careening through an action-packed roller-coaster course or racing in futuristic high-speed hovercars.<br /> <br /> Choose your adventure: <ul> <li>Cosmic Race </li><li>Bermuda Triangle </li><li>Solar Coaster </li><li>Grand Prix Raceway </li><li>Astro Canyon </li><li>Glacier Run. </li></ul><br /><strong>Note:</strong> Simulator accommodates up to 8 people per ride. Children must be 42 inches tall unless riding with an adult.<br /> <br /> Open the same hours as museum. <br/><br/><b>Categories</b>:&nbsp;Kids &amp; Families <br/><b>Sponsor</b>:&nbsp;<a href=\"http://si.edu/Museums/american-history-museum\" target=\"_blank\">American History Museum</a> <br/><b>Venue</b>:&nbsp;American History Museum <br/><b>Event Location</b>:&nbsp;Lower Level, across from the Stars and Stripes Cafe <br/><b>Cost</b>:&nbsp;Tickets always available for purchase at the entrance to the simulator gallery and may also be available at either Welcome desk.,   <strong>Admission Per Ride</strong>,  - $7.00 per person,   <strong>Payment Options:</strong>,  - Cash, VISA, and MasterCard <br/><br/>",
      "link"=>
       {"rel"=>"alternate",
        "type"=>"text/html",
        "href"=>"http://www.si.edu/Events/Calendar/?trumbaEmbed=view%3devent%26eventid%3d113256645"},
      "author"=>{"name"=>"Smithsonian Events"},
      "transparency"=>{"value"=>"http://schemas.google.com/g/2005#event.transparent"},
      "where"=>{"valueString"=>""},
      "when"=>{"startTime"=>"2016-12-29T15:00:00Z", "endTime"=>"2016-12-29T15:00:00Z"},
      "formatteddatetime"=>"Thursday, December 29, 2016, 10am",
      "notes"=>
       "<b>Ride Simulators:</b> (ride approximately 5 min.)\n Take an exciting virtual trip on board one of four simulators. Experience the thrill of careening through an action-packed roller-coaster course or racing in futuristic high-speed hovercars.\n \n Choose your adventure: <ul> \t<li>Cosmic Race</li> \t<li>Bermuda Triangle</li> \t<li>Solar Coaster</li> \t<li>Grand Prix Raceway</li> \t<li>Astro Canyon</li> \t<li>Glacier Run.</li> </ul><br /><b>Note:</b> Simulator accommodates up to 8 people per ride. Children must be 42 inches tall unless riding with an adult.\n \n Open the same hours as museum.",
      "eventtype"=>"Smithsonian Event",
      "eventimage"=>"https://www.trumba.com/i/DgAHpKWfrVg8g4XnmvDi23U%2A.jpg",
      "categories"=>"Kids & Families",
      "categoriesicon"=>"https://www.trumba.com/i/DgDVQZk%2A9xrnSqQZBtufuSoe.gif",
      "sponsor"=>"American History Museum",
      "venue"=>"American History Museum",
      "eventlocation"=>"Lower Level, across from the Stars and Stripes Cafe",
      "cost"=>
       "Tickets always available for purchase at the entrance to the simulator gallery and may also be available at either Welcome desk.\n \n <b>Admission Per Ride</b>\n - $7.00 per person\n \n <b>Payment Options:</b>\n - Cash, VISA, and MasterCard",
      "cateoryCalendar"=>"American History Museum|Ongoing Tours & Activities"},
     {"id"=>"http://uid.trumba.com/event/115828014",
      "masterId"=>"http://uid.trumba.com/master/115827586",
      "published"=>"2016-12-29T15:00:00Z",
      "updated"=>"2016-12-29T15:00:00Z",
      "category"=>{"scheme"=>"http://schemas.google.com/g/2005#kind", "term"=>"http://schemas.google.com/g/2005#event"},
      "title"=>"Spark!Lab",
      "content"=>
       "Thursday, December 29, 2016, 10am&nbsp;&ndash;&nbsp;4pm <br/><br/>Spark!Lab is where museum visitors become inventors. The Lemelson Center for the Study of Invention and Innovation invites children between the ages of 6 and 12 to create, collaborate, explore, test, experiment and invent. Activities for children and families incorporate traditional science, technology, engineering and math (STEM) with art, history and creativity.<br /> <br /> Spark!Lab activities are designed around common themes that connect to National Museum of American History collections and exhibitions. Themes are developed broadly to incorporate a wide range of collections and will change on a regular basis, ensuring that regular visitors have something new to explore.&#160; <br/><br/><b>Categories</b>:&nbsp;Kids &amp; Families <br/><b>Sponsor</b>:&nbsp;<a href=\"http://si.edu/Museums/american-history-museum\" target=\"_blank\">American History Museum</a> <br/><b>Co-sponsor</b>:&nbsp;Lemelson Center for the Study of Invention and Innovation <br/><b>Venue</b>:&nbsp;American History Museum <br/><b>Event Location</b>:&nbsp;Spark!Lab, First Floor, West Wing <br/><b>Cost</b>:&nbsp;Free; first come, first served. <br/><b>Related Exhibition</b>:&nbsp;Places of Invention, Inventive Minds, Landmark Object: Ralph Baer&#39;s Workshop, Inventing in America <br/><b>More info</b>:&nbsp;<a href=\"http://invention.si.edu/current-sparklab-activities\" target=\"_blank\" title=\"http://invention.si.edu/current-sparklab-activities\">invention.si.edu&#8230;</a> <br/><br/>",